language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

addons:
  apt:
    packages:
      - libreadline-dev # for lua
      - bison # for ruby

install:
  - pip --version
  - sudo -H pip install scan-build

script:
  - cargo build || travis_terminate 1
  - cargo test || travis_terminate 1
  - ./tests/all.sh