language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

install:
  - pip --version
  - pip install --upgrade pip
  - pip install scan-build

script:
  - ./tests/all.sh