language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

addons:
  apt:
    packages:
      - python3-pip
      - libreadline-dev

install:
  - pip3 --version
  - pip3 install scan-build

script:
  - ./tests/all.sh