language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

addons:
  apt:
    packages:
#      - python3-pip
      - libreadline-dev

install:
  - pip --version
  - sudo -H pip install scan-build

script:
  - cargo build || travis_terminate 1
  - ./tests/all.sh