language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

install:
  - pip3 --version
  - pip3 install --upgrade pip
  - pip3 install scan-build

script:
  - ./tests/all.sh