[package]
name = "cctrace"
version = "0.1.0"
authors = ["Per Larsen <perl@immunant.com>"]
edition = "2018"

[dependencies]
nom = "^4"
clap = "^2"
tempfile = "^3"
serde = "*"
serde_derive = "^1"
serde_json = "^1"